//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbOgrenciBilgiSistemiEntities : DbContext
    {
        public DbOgrenciBilgiSistemiEntities()
            : base("name=DbOgrenciBilgiSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_BOLUMLER> TBL_BOLUMLER { get; set; }
        public virtual DbSet<TBL_DERSLER> TBL_DERSLER { get; set; }
        public virtual DbSet<TBL_NOTLAR> TBL_NOTLAR { get; set; }
        public virtual DbSet<TBL_OGRENCI> TBL_OGRENCI { get; set; }
        public virtual DbSet<TBL_OGRENCIBOLUMLISTESI> TBL_OGRENCIBOLUMLISTESI { get; set; }
        public virtual DbSet<TBL_OGRENCIDERSLISTESI> TBL_OGRENCIDERSLISTESI { get; set; }
        public virtual DbSet<TBL_OGRETMENLER> TBL_OGRETMENLER { get; set; }
    }
}
