//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OGRENCIBOLUMLISTESI
    {
        public int ID { get; set; }
        public Nullable<int> OGRENCI { get; set; }
        public Nullable<int> BOLUM { get; set; }
        public string OGRENCINO { get; set; }
    
        public virtual TBL_BOLUMLER TBL_BOLUMLER { get; set; }
        public virtual TBL_OGRENCI TBL_OGRENCI { get; set; }
    }
}
