//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DERSLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DERSLER()
        {
            this.TBL_NOTLAR = new HashSet<TBL_NOTLAR>();
            this.TBL_OGRENCIDERSLISTESI = new HashSet<TBL_OGRENCIDERSLISTESI>();
        }
    
        public int ID { get; set; }
        public string DERS { get; set; }
        public string DERSKODU { get; set; }
        public Nullable<int> BOLUM { get; set; }
        public Nullable<int> OGRETMEN { get; set; }
        public Nullable<decimal> KREDI { get; set; }
        public string DERSLIK { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBL_OGRETMENLER TBL_OGRETMENLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_NOTLAR> TBL_NOTLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OGRENCIDERSLISTESI> TBL_OGRENCIDERSLISTESI { get; set; }
        public virtual TBL_BOLUMLER TBL_BOLUMLER { get; set; }
    }
}
