//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OGRETMENLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_OGRETMENLER()
        {
            this.TBL_DERSLER = new HashSet<TBL_DERSLER>();
            this.TBL_OGRENCIDERSLISTESI = new HashSet<TBL_OGRENCIDERSLISTESI>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<int> BOLUM { get; set; }
        public string SICILNO { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBL_BOLUMLER TBL_BOLUMLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DERSLER> TBL_DERSLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OGRENCIDERSLISTESI> TBL_OGRENCIDERSLISTESI { get; set; }
    }
}
